[[redirects]]
  from = "/*"
  to = "https://goerli.launchpad.ethereum.org"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
